name: Compilar APK Android

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar Dependencias
        run: |
          npm install
          npm run build

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Inicializar Capacitor e Android
        run: |
          npx cap init "Gaming Hub" "com.nexus.gaminghub" --web-dir dist
          npx cap add android
          
          # Injetar permissoes nativas no AndroidManifest.xml
          MANIFEST_PATH="android/app/src/main/AndroidManifest.xml"
          sed -i '/<\/manifest>/i \    <uses-permission android:name="android.permission.KILL_BACKGROUND_PROCESSES" \/>' $MANIFEST_PATH
          sed -i '/<\/manifest>/i \    <uses-permission android:name="android.permission.PACKAGE_USAGE_STATS" \/>' $MANIFEST_PATH
          sed -i '/<\/manifest>/i \    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" \/>' $MANIFEST_PATH
          sed -i '/<\/manifest>/i \    <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY" \/>' $MANIFEST_PATH

          npx cap sync android

      - name: Compilar Ficheiro APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Disponibilizar Ficheiro APK
        uses: actions/upload-artifact@v4
        with:
          name: GamingHub-Installer-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk

